export const DATA = [
  {
    id: 1,
    location: "Greendale, Hre",
    contact: "0771234567",
    myImage: "/images/2.WEBP",
    description: "Fix a sink leakage",
    fee: 10,
  },
  {
    id: 2,
    location: "Highlands, Hre",
    contact: "0771234567",
    myImage: "/images/1.jpg",
    description: "Pool cleaning",
    fee: 15,
  },
  {
    id: 3,
    location: "Chisipite, Hre",
    contact: "0771234567",
    myImage: "/images/1.jpg",
    description: "Pool cleaning",
    fee: 20,
  },
  {
    id: 4,
    location: "Chishawasha, Hre",
    contact: "0771234567",
    myImage: "/images/2.WEBP",
    description: "Fix a sink leakage",
    fee: 5,
  },
  {
    id: 5,
    location: "Poland, Hre",
    contact: "0771234567",
    myImage: "/images/1.jpg",
    description: "Pool cleaning",
    fee: 20,
  },
  {
    id: 6,
    location: "Enterprise, Hre",
    contact: "0771234567",
    myImage: "/images/1.jpg",
    description: "Pool cleaning",
    fee: 20,
  },
];

export const TASKERDATA = [
  {
    id: 1,
    image: "./images/john.webp",
    name: "Jane Doe",
    review: 100,
    completed: 30,
    skill1: "Help Moving",
    skill2: "Pool Cleaning",
    skill3: "Grass Cutting",
    description: "I have experience and skills to help out with anything.",
  },
  {
    id: 2,
    image: "./images/bob.webp",
    name: "Bob Builder",
    review: 98,
    completed: 17,
    skill1: "Brick Laying",
    skill2: "Furniture Mounting",
    skill3: "Painting",
    description:
      "With over 3 years of tasking, I can help with anything you may need.",
  },
  {
    id: 3,
    image: "./images/john.webp",
    name: "Trish Match",
    review: 97,
    completed: 22,
    skill1: "Driving",
    skill2: "Car Washing",
    skill3: "Gardening",
    description:
      "I have been tasking for years and based on my rating and reviews, I am very reliable.",
  },
];
